# Generated by Django 3.1.7 on 2021-03-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accessible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=50)),
                ('name_2', models.CharField(max_length=50)),
                ('name_3', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('door_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ul_map_backend.door')),
                ('door_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ul_map_backend.door')),
                ('door_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ul_map_backend.door')),
                ('door_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ul_map_backend.door')),
            ],
        ),
    ]
