# Generated by Django 3.1.7 on 2021-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ul_map_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
