# Generated by Django 3.1.7 on 2021-03-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ul_map_backend', '0002_auto_20210303_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='door_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ul_map_backend.door'),
        ),
        migrations.AlterField(
            model_name='location',
            name='door_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ul_map_backend.door'),
        ),
        migrations.AlterField(
            model_name='location',
            name='door_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ul_map_backend.door'),
        ),
        migrations.AlterField(
            model_name='location',
            name='door_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ul_map_backend.door'),
        ),
    ]
