# Generated by Django 3.1.7 on 2021-04-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ul_map_backend', '0003_auto_20210303_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='eircode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
